
import { createClient } from '@supabase/supabase-js';
import '../globals.css'
import SupabaseProvider from './services/supabaseconnection';
import { useSupabase } from './services/supabaseconnection';
import { ChakraProviders } from '../chakraProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const supdb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

  const {data:{session}} = await supdb.auth.getSession();
  return (
    <html lang="en">
      <body>
        {/* <SupabaseProvider session={session}>
        {children}
        </SupabaseProvider> */}
        <ChakraProviders>
          {children}
        </ChakraProviders>
      </body>
    </html>
  )
}
